services:
  db:
    image: postgres:13
    container_name: pg13-sitemadefacturacion
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - django-facturacion

  redis:
    container_name: redis-sistemadefacturacion
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - django-facturacion

  web:
    image: vendo_sri_web  
    container_name: vendo_sri_web
    command: gunicorn vendo_sri.wsgi:application --bind
    volumes:
      - static_volumen:/app/staticfiles
      - media_volumen:/app/mediafiles
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - django-facturacion
      - general-net
    

volumes:
  postgres_data:
  static_volumen:
  media_volumen:

networks:
  django-facturacion:
    driver: bridge
  general-net:
    external: true